"""
SmartCart AI Engineering Lab: Flyer Ingestion, Normalization & Feature Pipeline
Target: M6P 0C2 (Junction Triangle, Toronto)
Files Used: costco.csv, food_basics.csv, freshco.csv, no_frills.csv
"""

import re
import numpy as np
import pandas as pd

# ==============================================================================
# 0. INITIAL DATA INGESTION (SETUP)
# ==============================================================================
# Load the 4 store datasets generated by your extraction scraper
sample_path = "grocery_data_M6P0C2/"
store_files = {
    "Costco": sample_path+"costco.csv",
    "Food Basics": sample_path+"food_basics.csv",
    "FreshCo": sample_path+"freshco.csv",
    "No Frills": sample_path+"no_frills.csv",
}

raw_dfs = []
for store_name, filepath in store_files.items():
    try:
        temp_df = pd.read_csv(filepath)
        raw_dfs.append(temp_df)
    except FileNotFoundError:
        print(f"[-] Warning: {filepath} not found. Ensure CSVs exist in current directory.")

# ==============================================================================
# SPRINT 1 PRACTICE: PRODUCTION PANDAS & FEATURE NORMALIZATION
# ==============================================================================

# Q1 [Multi-Store Ingestion & Schema Alignment]:
# Context: Raw circular feeds arrive from different grocers as individual files.
# Business / ML Purpose: Consolidate multiple merchant streams into a single unified
#                        master DataFrame so downstream operations apply uniformly across all stores.
# Expected Pandas Skill: `pd.concat(..., ignore_index=True)`
# Task: Concatenate all DataFrames in `raw_dfs` into a single DataFrame named `df_raw`.
#       Print the total record count and the count of items per store using `.value_counts()`.
# ------------------------------------------------------------------------------
# Your solution:

df_raw=pd.concat(raw_dfs,ignore_index=True)
len(df_raw) # 1013
df_raw.info()
df_raw.groupby('store')['item_id'].count()
df_raw['name'].value_counts()
#store
# Costco         286
# Food Basics    302
# FreshCo        145
# No Frills      280
# Name: item_id, dtype: int64
# Q2 [Data Cleansing & Missing Value Purging]:
# Context: Web scrapers occasionally extract non-product banners (e.g., store hours)
#          or items with unlisted prices that will corrupt mathematical ranking.
# Business / ML Purpose: Remove non-actionable rows before training or indexing.
# Expected Pandas Skill: `.dropna(subset=[...])` and `pd.to_numeric(..., errors='coerce')`
# Task: Create a new DataFrame `df_clean` from `df_raw` where:
#       1. Rows with NaN in 'name' or 'price' are dropped.
#       2. The 'price' column is cast to float numeric type.
#       3. Rows with price <= 0.0 are filtered out.
# ------------------------------------------------------------------------------
# Your solution:

df_clean = df_raw.dropna(subset=['name', 'price']).copy() 
df_clean['price']=pd.to_numeric(df_clean['price'],errors='coerce')
df_clean = df_clean.dropna(subset=['price'])
# 937 rows × 19 columns used to be 1013 x 19 
df_clean = df_clean[df_clean['price'] >0]
# Q3 [Vectorized Deduplication & Temporal Consistency]:
# Context: Multiple scrape passes or multi-page circulars can duplicate identical item listings.
# Business / ML Purpose: Ensure each product deal appears exactly once per flyer cycle
#                        to avoid skewed statistics and duplicate search results.
# Expected Pandas Skill: `.drop_duplicates(subset=[...], keep='first')`
# Task: Deduplicate `df_clean` in-place based on the subset:
#       ['store', 'name', 'price', 'valid_to'].
#       Verify how many unique items remain.
# ------------------------------------------------------------------------------
# Your solution:
duplicates_subset = ['store', 'name', 'price', 'valid_to']
df_clean.drop_duplicates(subset=duplicates_subset,keep='first',inplace=True)
# still 937
df_clean['name'].value_counts()
# Q4 [Vectorized Regex Extraction: Package Quantities & Units]:
# Context: Product sizes are trapped inside unstructured name strings
#          (e.g., "AASHIRVAAD WHOLE WHEAT FLOUR, 9.07 kg", "Armstrong Cheese Snacks 210 g", "Allen's Apple Juice 1.89 L").
# Business / ML Purpose: Extract numeric size and unit tokens into dedicated columns to calculate unit economics.
# Expected Pandas Skill: Vectorized regex extraction with `.str.extract(pattern, flags=re.IGNORECASE)`
# Task: In `df_clean`, create two new columns:
#       - 'pkg_qty' (float): The numeric quantity (e.g., 9.07, 210, 1.89)
#       - 'pkg_unit' (str, lowercased): The unit string (e.g., 'kg', 'g', 'l', 'ml', 'lb', 'oz', 'count')
#       Hint: Write a regex with two capture groups for number and unit.
# ------------------------------------------------------------------------------
# Your solution:

#'pkg_qty'
df_clean['name']
# Q5 [Unit Standardization to Base Metric System (Grams / Milliliters)]:
# Context: Different grocers advertise in conflicting units (kg vs g vs lb vs L vs ml).
#          Comparing $13.00 for 9.07 kg against $4.49 for 210 g is impossible without a common base.
# Business / ML Purpose: Convert all mass/volume units into standard base units:
#                        - 'kg' -> multiply by 1000.0 (grams)
#                        - 'l'  -> multiply by 1000.0 (milliliters)
#                        - 'lb' -> multiply by 453.592 (grams)
#                        - 'oz' -> multiply by 28.3495 (grams)
# Expected Pandas Skill: Dictionary mapping with `.map()` and vectorized multiplication.
# Task: 1. Create a column 'unit_multiplier' using a dictionary lookup on 'pkg_unit'.
#       2. Compute 'norm_size_base' = 'pkg_qty' * 'unit_multiplier'.
# ------------------------------------------------------------------------------
# Your solution:

# Conversion factors to standard base units (grams and milliliters)
unit_conversion = {
    'kg': 1000.0,
    'l': 1000.0,
    'lb': 453.592,
    'oz': 28.3495,
    'g': 1.0,
    'ml': 1.0,
}

# 1. Map conversion multipliers (defaults to 1.0 for units already at base or unlisted)
df['unit_multiplier'] = df['pkg_unit'].str.lower().map(unit_conversion).fillna(1.0)

# 2. Vectorized multiplication for standardized base quantity
df['norm_size_base'] = df['pkg_qty'] * df['unit_multiplier']
# Q6 [Normalized Unit Economics ($ / 100g or $ / 100ml)]:
# Context: Consumers need to know the *true* cheapest option regardless of package size.
# Business / ML Purpose: Compute a standardized unit cost ($ / 100g or $ / 100ml) so ranking algorithms
#                        can objectively sort deals by value.
# Expected Pandas Skill: Vectorized conditional arithmetic with `np.where(condition, if_true, if_false)`.
# Task: Create a column 'cost_per_100_base' in `df_clean` calculated as:
#       (price / norm_size_base) * 100
#       Only calculate where 'norm_size_base' > 0; otherwise assign `np.nan`.
# ------------------------------------------------------------------------------
# Your solution:


# Q7 [Vectorized Macro & Grocery Category Tagging]:
# Context: Users will ask SmartCart high-level semantic questions like:
#          "Where can I get high-protein meal prep ingredients?" or "What fresh produce is on sale?"
# Business / ML Purpose: Tag items into primary categories without slow Python `for` loops.
# Expected Pandas Skill: Regex matching via `.str.contains(regex_pattern, case=False, na=False, regex=True)`
# Task: In `df_clean`, create two boolean columns:
#       - 'is_protein': True if the item name contains chicken, beef, pork, salmon, tuna, egg, paneer, tofu, yogurt, lentils, etc.
#       - 'is_produce': True if the item name contains apple, banana, tomato, potato, onion, spinach, mushroom, cucumber, etc.
# ------------------------------------------------------------------------------
# Your solution:


# Q8 [Department Noise Capping & Non-Grocery Filtering]:
# Context: Big-box stores (Costco, Walmart) mix high-ticket merchandise (sofas, luggage, electronics)
#          with groceries, which severely skews price analytics.
# Business / ML Purpose: Filter out non-food items to keep our grocery index clean.
# Expected Pandas Skill: Boolean masking and percentile clipping (`.clip()` or condition filtering).
# Task: 1. Identify items priced above $50.00.
#       2. Create a filtered DataFrame `df_groceries` containing only items where `price <= 50.00`
#          OR items flagged as 'is_protein' == True or 'is_produce' == True.
# ------------------------------------------------------------------------------
# Your solution:


# Q9 [Cross-Store Value Aggregation & GroupBy Insights]:
# Context: We need to benchmark which store currently offers the best deals in the Junction Triangle.
# Business / ML Purpose: Provide aggregate analytics for dashboard reporting and basket planning.
# Expected Pandas Skill: `.groupby('store').agg(...)`
# Task: Group `df_groceries` by 'store' and calculate:
#       - Total items available
#       - Median grocery price
#       - Count of high-protein items
#       - Average 'cost_per_100_base' for protein items
#       Sort the output table by total high-protein items in descending order.
# ------------------------------------------------------------------------------
# Your solution:


# Q10 [Semantic Document Chunking for Vector Store (ChromaDB / LLM)]:
# Context: Dense vector search models perform best when metadata is embedded in clear, structured natural language strings.
# Business / ML Purpose: Build the exact text string that will be converted into embeddings for our vector database.
# Expected Pandas Skill: Vectorized string concatenation using Pandas Series `+` operators and `.fillna()`.
# Task: In `df_groceries`, create a new column 'embedding_chunk' formatted as:
#       "Store: {store} | Product: {name} | Brand: {brand} | Price: ${price} | Valid until: {valid_to}"
#       (Ensure missing brands display as 'N/A' rather than NaN).
#       Display 3 sample chunks.
# ------------------------------------------------------------------------------
# Your solution:


# ==============================================================================
# VERIFICATION BLOCK (Run when all questions are completed)
# ==============================================================================
if __name__ == "__main__":
    print("[*] SmartCart AI Engineering Lab initialized.")
    print("[*] Open this file and solve Q1 through Q10 sequentially.")